name: CI

on:
  push:    { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.8' }

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run combined tests
        # Option A: Module invocation
        run: python -m src.CombinedTests --part all

        # Or, if you prefer to run the script directly (Option B),
        # make sure you included the sys.path hack above:
        # run: python src/CombinedTests.py --part all
